FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24.5@sha256:267159cb984d1d034fce6e9db8641bf347f80e5f2e913561ea98c40d5051cb67 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-opentofu"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-opentofu"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-opentofu"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-opentofu"

ARG TARGETOS
ARG TARGETARCH
ARG TOFU_VERSION

# renovate: datasource=github-releases depName=opentofu/opentofu
ENV TOFU_VERSION="${TOFU_VERSION:-v1.10.3}"

RUN apk --update add --virtual .build-deps libarchive-tools && \
    apk add --no-cache curl git openssh-client && \
    curl -SsfL "https://github.com/opentofu/opentofu/releases/download/${TOFU_VERSION}/tofu_${TOFU_VERSION##v}_linux_${TARGETARCH}.zip" | \
        bsdtar -xf - -C /usr/local/bin tofu && \
    chmod 755 /usr/local/bin/tofu && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/wp-opentofu /bin/wp-opentofu
ENTRYPOINT ["/bin/wp-opentofu"]
