FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:2bd56f00ff47baf33e64eae7996b65846c7cb5e0a46e0a882ef179fd89654afa as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/alpine:3.20@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-opentofu"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-opentofu"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-opentofu"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-opentofu"

ARG TARGETOS
ARG TARGETARCH
ARG TOFU_VERSION

# renovate: datasource=github-releases depName=opentofu/opentofu
ENV TOFU_VERSION="${TOFU_VERSION:-v1.8.1}"

RUN apk --update add --virtual .build-deps libarchive-tools && \
    apk add --no-cache curl git openssh-client && \
    curl -SsfL "https://github.com/opentofu/opentofu/releases/download/${TOFU_VERSION}/tofu_${TOFU_VERSION##v}_linux_amd64.zip" | \
        bsdtar -xf - -C /usr/local/bin tofu && \
    chmod 755 /usr/local/bin/tofu && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/wp-opentofu /bin/wp-opentofu
ENTRYPOINT ["/bin/wp-opentofu"]
